name: workflow_dispatch_with_input

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Run tests on which environment
        default: production
      testsuite:
        description: Choose which test suite to run
        default: All
        type: choice
        options:
          - E2E
          - API
          - All

jobs:
  workflow_with_input:
    runs-on: ubuntu-latest
    steps:
      - name: run with input
        run: |
          echo "${{github.event.inputs.testsuite}}"

      # Run e2e tests
      - name: 🧪 Running the e2e tests
        id: e2e-test
        if: success() && (github.event.inputs.testsuite == 'E2E' || github.event.inputs.testsuite == 'All')
        run: |
          echo running e2e tests
      # Run API tests
      - name: 🧪 Running the api tests
        id: api-test
        if: always() && (github.event.inputs.testsuite == 'API' || github.event.inputs.testsuite == 'All')
        timeout-minutes: 5
        run: |
          echo running api tests
